// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(MFADbContext))]
    partial class MFADbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthenCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("CHAR");

                    b.Property<DateTime>("CodeExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("826ab012-3c57-4abc-a399-807d5961ffe3"),
                            AuthenCode = "000000",
                            CodeExpireTime = new DateTime(2023, 6, 18, 18, 18, 19, 529, DateTimeKind.Utc).AddTicks(3874),
                            FullName = "Test user one",
                            Password = "$2a$11$PzF3uBGA4gN8A3B0EjVLpObew8R6v6xObZZq797gUxDotzzZNn.wG",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("2dfd1e1e-7cfd-4580-92d3-f01fe17b7159"),
                            AuthenCode = "000000",
                            CodeExpireTime = new DateTime(2023, 6, 18, 18, 18, 19, 798, DateTimeKind.Utc).AddTicks(8725),
                            FullName = "Test user two",
                            Password = "$2a$11$XoK9fp8FyIhNkaFL9nOwc.oAffLISUAUpfsaUR7dQ.eBZG9DQF7WC",
                            UserName = "user2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
